<head>
	<title>Consejos</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="css/styles.css">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1">
	<!-- Tipografías -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500&display=swap" rel="stylesheet">
</head>

		<h1>Consejos para ayudar a alguien con ansiedad</h1>
		<p style="margin-top: 30px;"> Estos consejos no solo están destinados a quien quiera ayudar a alguien con ansiedad, se trata de intentar trabajar la empatía en cualquier situación en la que quieras ayudar a una persona que se encuentra en un mal momento, ya sea con ansiedad o no.
		</p>
		<br><br>
		<p>- No hagas sentir a esa persona que lo que siente está mal o que “no es para tanto”. Probablemente no lo estés haciendo conscientemente, pero por ello tienes que pensar y tener cuidado con las palabras que usas cuando una persona está teniendo problemas. Tienes que entender que cada persona tiene sus problemas y para ellxs son importantes, por lo que hay que tratar de entender por lo que están pasando y cómo se pueden sentir. Cualquier sentimiento es válido y aunque te puedan parecer descabellados, esa persona lo está pasando mal y no hay que hacerle sentir diferente por lo que siente o piensa, ni infravalorar sus problemas, se puede dar nuestra opinión de una manera respetuosa hacia la persona y sus sentimientos, dejándole claro que es normal sentirse así, ya que las personas con ansiedad tendemos a pensar que estamos “locxs” o que no deberíamos pensar/sentir esas cosas. Intenta ser paciente y, como todo el mundo cuando lo está pasando mal, solo necesitamos apoyo y mucho amor.</p>
		<br><br>
		<p>- Intenta ayudar a esa persona a controlar su respiración. Sobre todo, en un momento en el que vemos que esa persona puede estar teniendo un ataque de ansiedad. Es normal si te sientes asustado o no entiendes muy bien qué está pasando. Explicándolo brevemente, es un momento en el que te abruman tus emociones/pensamientos o un momento en el que te sobrepasa todo, como una situación agobiante para esa persona o en la que ha sentido una avalancha de miedo. Esa persona también puede estar confundida y no saber en el momento qué está pasando, por eso es importante reaccionar de una manera adecuada para ayudar a la otra persona. Aunque en ese momento estés asustadx, es mejor mostrar la mayor naturalidad ante la situación posible, que la persona afectada vea a la otra persona alterada puede hacer que el ataque vaya a peor, no significa que tengas que estar bien, sino intentar mostrarte calmadx y dejar ver que no es una situación en la que se tenga que sentir miedo. Con esto se quiere decir, que cuando una persona está teniendo un ataque suele pensar que está causando una escena, y para ayudar podemos empezar a normalizar esta situación. Se necesitan unos minutos y algo de ayuda para recuperarse, es una reacción que no se puede evitar y no tiene nada de malo. Esto dicho, algo que suele ayudar es guiar la respiración de esa persona, ya que la respiración hace mucho en una situación así. Se puede intentar acercar a la persona y guiar la respiración también con contacto físico, aunque también puede ser simplemente con palabras, diciéndole cuando inspirar y hacerlo contigo. Esta técnica suele ser bastante efectiva para que esa persona consiga calmarse y estar más preparadx para tratar con el tema. Puede servir en más situaciones aparte de los ataques de ansiedad, como en momentos en los que alguien se encuentre muy alteradx, con mucho miedo, etc.</p>
		<br><br>
		<p>- No dejes pensar a esa persona que está reaccionando exageradamente. Esa persona no puede evitar sentirse de esa manera, si pudiera elegir cómo reaccionar a las cosas o qué sentir, te aseguro que no sería así. Si sientes que está reaccionando especialmente mal a alguna situación probablemente haya cosas mucho más profundas de las que podemos ver. Para esto, lo mejor sería intentar hablarlo con la persona de la manera más calmada posible. El tono de voz puede ser algo que ayude mucho a la situación, por lo que mantenerte con un tono calmado puede hacer sentir a esa persona más segura a la hora de comunicarse. Intenta mantenerte paciente y entender lo máximo a la otra persona, además de dejar claro a la otra persona que también tiene que hacer el esfuerzo por escuchar calmadamente tus sentimientos ante la situación. Lo ideal sería hablarlo tomando turnos para cada uno, explicando cómo os habéis sentido de manera asertiva, sin culpar al otro. Dejando claras tus intenciones de arreglar las cosas juntos puedes preguntar el porqué de la reacción y tratar de llegar a un punto en el que ambos os sintáis bien. Simplificando, la clave es la comunicación asertiva y tratar de arreglar el problema juntos.</p>
		<br><br>
		<p>- Pregunta qué es lo que necesita la persona en momentos predeterminados. Esto puede ayudar en muchas ocasiones. Algunas veces se quiere hablar del tema y otras se puede preferir estar en silencio durante un rato. Es importante siempre respetar lo que quiere esa persona en el momento, pero con la intención de continuar en algún momento la conversación, nunca huyendo o dejando pasar el tema. </p>
		<br><br>
		<p>- No forzarle a hablar o a hacer algo que no se sienta preparadx. Se puede animar a hacer algo que le dé ansiedad, pero tampoco forzar. Con esto, lo que se quiere decir es que, si hay una situación que a esa persona le da ansiedad y/o miedo, se puede animar a que en algún momento lo haga, dando consejos de cómo puede hacerlo hasta que se sienta preparadx. Pero nunca criticarle por no poder hacerlo o hacerlo ver como una tontería, es una situación estresante para esa persona y solo quiere tener apoyo de que en algún momento podrá hacerlo. </p>