<head>
	<title>Consejos</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="css/styles.css">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1">
	<!-- Tipografías -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500&display=swap" rel="stylesheet">
</head>
		
		<h1>Consejos para calmar tu ansiedad</h1>
		<p style="margin-top: 30px;">- Si tienes la oportunidad de tener ayuda profesional, la mejor decisión es cogerla. Esto puede que te dé miedo o vergüenza, es completamente normal. Contar tus problemas es algo que puede costar, pero te ayudará a largo plazo. Se puede empezar con cómo te sientes en la propia consulta, y de ahí coger confianza para profundizar más. También es algo importante escoger detenidamente a qué psicólogo vas a ir, si en un tiempo solo ves que te sientes peor contigo mismo y no te sientes en un sitio seguro, lo mejor sería cambiar de profesional. Es completamente comprensible que una mala experiencia te haga venirte abajo e incluso pensar que no te pueden ayudar, pero te puedo asegurar que eso no es así, simplemente no has encontrado el psicólogo apropiado para ti, todo el mundo puede mejorar teniendo la ayuda adecuada :)</p>
		<br><br>
		<p>- No rechaces tus pensamientos ni intentes huir de ellos. Con una búsqueda rápida en Internet nos encontramos con numerosas preguntas de “cómo curar tu ansiedad” buscando deshacerte de ella lo más pronto posible. Con esto estamos fomentando que no nos guste nuestra persona, diciéndonos que lo que sentimos no es válido y hay que deshacerse de ello cuánto antes. Estos sentimientos y pensamientos forman parte de nosotros y hay que aprender a abrazarlos como a nosotros mismos.</p>
		<br><br>
		<p>- Intenta aceptar tu ansiedad. Claro, esto suena genial en teoría, pero en la práctica puede ser algo sumamente difícil. No es algo que se pueda inculcar inmediatamente, conllevará trabajo y esfuerzo. Hay que tener en cuenta que los pensamientos que esta genera no son necesariamente algo malo, sino que se trata de un mecanismo de protección de tu cuerpo de algo que identifica como una amenaza, por lo que, con práctica y mucho amor, podemos intentar analizar esos pensamientos sin juzgarlos. No hay que rechazarlos, incluso aunque nos parezcan incorrectos, con eso solo conseguiríamos repudiarlos aún más. La ansiedad forma parte de nosotros y hay que cuidarla como al resto de nuestra persona, solo hay que hacerlo de la manera adecuada. Como se ha dicho anteriormente, no se va a conseguir de inmediato, así que vamos a intentar poco a poco, en un momento en el que estemos más calmadxs, analizar de donde puede venir ese pensamiento y cómo poder comenzar a tratarlo las próximas veces. Es probable que las primeras veces que hagamos este proceso salgan malos pensamientos de por qué se ha pensado eso, por ello es mejor elegir un momento en el que estemos calmadxs y podamos ver las cosas desde otra perspectiva. El objetivo de esto es intentar normalizar esos pensamientos ya que son completamente válidos, lo importante es querer trabajar en ellos y lentamente acercarte más a la persona que quieres ser.</p>
		<br><br>
		<p>- Prueba técnicas de respiración. Esto nos puede ayudar en diversas situaciones, especialmente en momentos en los que estamos sobrepasados de pensamientos o muy alterados. Cuando nos encontremos en estas situaciones vamos a intentar parar lo que estemos haciendo y concentrarnos completamente en nuestra respiración. En el momento, la respiración probablemente esté algo alterada, por lo que, vamos a centrarnos en inspirar durante 5 segundos y expirar otros 5, hasta que no te sientas más calmadx no pares de hacer el ejercicio. Estando ya tranquilx se puede pensar con más claridad y razonar. <br> Estas técnicas no solo valen para cuando se está alterado, la meditación diaria puede tener multitud de beneficios. Se puede hacer por las mañanas, cuando te hayas levantado, encender una vela (opcionalmente) para representar la luz que nos va a guiar durante el día y concentrarte con los ojos cerrados en tu respiración unos 5 min, intentando dejar ir tus pensamientos y relajarte. Hacer esto al comenzar tus mañanas te puede ayudar a lo largo del día a estar más relajadx y así poder ordenar nuestros pensamientos de manera más calmada y positiva.</p>
		<br><br>
		<p>- Háblalo con otras personas. En algunos momentos es mejor desahogarse con alguien y sentirse escuchadx para poder estar mejor, pero esto dependiendo de cómo se haga. Desahogarse con alguien siempre está bien, sin embargo, es importante que no le pongas la responsabilidad de tus problemas a la otra persona para que te los resuelva. Hay que tener siempre presente que solo nosotros somos los responsables de nuestros propios problemas o miedos, esto no significa que no podamos pedir consejo, sino que no debemos esperar a que te resuelvan los problemas o se resuelvan solos. También puede ser que la otra persona no responda de la mejor manera, por eso hay que saber que nuestros problemas son completamente válidos y nadie puede opinar en cómo te sientes. Si no sientes que tengas la suficiente confianza con alguna persona o prefieres hablarlo de forma anónima, te invito a hablarlo en nuestro apartado de comentarios de manera segura :)</p>

		